baseURL = "https://gramin.pro"
languageCode = "en-us"
title = "ProGramin'g thoughts"
theme = "cactus"


[params]
  description = "My name is Maksim Gramin. I’m a software developer passionate about Databases and SQL."
  showProjectsList = true
  projectsUrl = "https://github.com/mgramin"
  disqusShortname = "mgramin"

[params.comments]
    enabled = true

[[params.social]]
  name = "github"
  link = "https://github.com/mgramin"

[[params.social]]
  name = "email"
  link = "mgramin@gmail.com" # no need for "mailto:" at the start

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/graminmaksim"

[[params.social]]
  name = "telegram"
  link = "https://t.me/sundquist"
