baseURL = "https://gramin.pro/"
languageCode = "en-us"
title = "ProGramin'g thoughts"
theme = "cactus"
disqusShortname = "gramin-pro"
googleAnalytics = "G-SZPJMEZSBE"
copyright = "Maksim Gramin"


[params]
  description = """
  My name is Maksim Gramin. I’m a software developer passionate about Databases and SQL.
  
  If you find any mistake, inaccuracy, or anything else, feel free to text me or [create a PR](https://github.com/mgramin/mgramin.github.io)."""
  showProjectsList = true
  showAllPostsOnHomePage = true
  # postsOnHomePage = 5
  projectsUrl = "https://github.com/mgramin"
  rss = true
  mainSection = "posts"

[params.comments]
  enabled = true

[[params.social]]
  name = "github"
  link = "https://github.com/mgramin"

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/graminmaksim"

[[params.social]]
  name = "email"
  link = "mgramin@gmail.com"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/maksim-gramin-a70ba05a"

[[params.social]]
  name = "telegram"
  link = "https://t.me/sundquist"

[[params.social]]
  name = "instagram"
  link = "https://www.instagram.com/pro_gramin"

[[params.social]]
  name = "reddit"
  link = "https://www.reddit.com/user/mgramin"


[[params.social]]
  name = "rss"
  link = "https://gramin.pro/index.xml"


[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "All posts"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 4
