baseURL = "https://gramin.pro"
languageCode = "en-us"
title = "ProGramin'g thoughts"
theme = "cactus"
disqusShortname = "mgramin"


[params]
  description = """
  My name is Maksim Gramin. I’m a software developer passionate about Databases and SQL.
  
  If you find a spelling mistake, inaccuracy, or anything else, feel free to text me or [create a PR](https://github.com/mgramin/mgramin.github.io)."""
  showProjectsList = true
  projectsUrl = "https://github.com/mgramin"
  disqusShortname = "mgramin"

[params.comments]
  enabled = true

[[params.social]]
  name = "github"
  link = "https://github.com/mgramin"

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/graminmaksim"

[[params.social]]
  name = "email"
  link = "mgramin@gmail.com"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/maksim-gramin-a70ba05a"

[[params.social]]
  name = "telegram"
  link = "https://t.me/sundquist"

[[params.social]]
  name = "instagram"
  link = "https://www.instagram.com/pro_gramin"
